# syntax=docker/dockerfile:1.7

ARG GO_IMAGE=golang@sha256:7ef941168f213aa115df2e61364d67682129e99dc8188b734139dea862cc7d31
ARG RUNTIME_IMAGE=gcr.io/distroless/static-debian12:nonroot

FROM --platform=$BUILDPLATFORM ${GO_IMAGE} AS builder

WORKDIR /src

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    set -eux; \
    goarm=""; \
    if [ "${TARGETARCH}" = "arm" ]; then \
      goarm="${TARGETVARIANT#v}"; \
    fi; \
    env \
      CGO_ENABLED=0 \
      GOOS="${TARGETOS:-linux}" \
      GOARCH="${TARGETARCH:-amd64}" \
      GOARM="${goarm}" \
      go build \
        -trimpath \
        -ldflags='-s -w -buildid=' \
        -o /out/microproxy-control \
        ./cmd/microproxy-control

FROM ${RUNTIME_IMAGE}

COPY --from=builder /out/microproxy-control /usr/local/bin/microproxy-control

ENTRYPOINT ["/usr/local/bin/microproxy-control"]
CMD ["-config", "/etc/microproxy/config.yaml", "-listen-addr", ":8081"]
